### ISSUE TITLE
Love this, but it really needs unintrospect-ns!

### ISSUE THREAD

**Issue by bitemyapp** [MichaelDrogalis/night-vision#1]
Single run of unit tests with a single ns introspected generated multiple megabytes of text :laughing:

**Comment by MichaelDrogalis** [comment]
Yeeeah, I understand. This happens any time you're not reloading the ns that has hooks attached. I'm not sure what the best solution for this is.

**Comment by MichaelDrogalis** [comment]
I think perhaps I can attach specially named hooks that will detach afterwards. I'll keep you posted, @bitemyapp.

**Comment by bitemyapp** [comment]
@MichaelDrogalis you can always solve your problems through the use of more metadata. Like violence.

**Comment by MichaelDrogalis** [comment]
@bitemyapp: I'll figure something out. :)

**Comment by MichaelDrogalis** [comment]
Nailed it!

**Comment by bitemyapp** [comment]
@MichaelDrogalis doing a cleaning run of stuff I'm not likely to act on, introspecting Clojure code is not something I've needed to do for awhile now. :stuck_out_tongue:
